### ISSUE TITLE
qrstr has no definition of EOLNType

### ISSUE THREAD

**Issue by freezernick** [Tricky1975/kitty#9]
https://github.com/Tricky1975/kitty/blob/63d0515ff7616813d1e2bb1ab38c0c32c399a5c4/Program.cs#L92

Did I screw up or did you forget to update your TrickyUnits repository? 😛

**Comment by Tricky1975** [comment]
The latter appears most likely.... It's a repository I often forget to update.... ;)

**Comment by Tricky1975** [comment]
And this has been fixed now, thank you ;)
